#ifndef GESTUREENUMERATION_HXX_INCLUDED
#define GESTUREENUMERATION_HXX_INCLUDED

enum HandFocus{
    Left,
    Right,
    Both
};

enum GestureType{
    WAVE_LEFT,
    WAVE_RIGHT,
    WAVE_UP,
    WAVE_DOWN,
    WAVE_DIAGONAL_UPPER_LEFT,
    WAVE_DIAGONAL_UPPER_RIGHT,
    WAVE_DIAGONAL_LOWER_LEFT,
    WAVE_DIAGONAL_LOWER_RIGHT,
    ZOOM_IN,
    ZOOM_OUT,
    ROTATE_CLOCKWISE,
    ROTATE_COUNTERCLOCKWISE,
    ROTATE_FRONT,
    ROTATE_BACK,
    NONE
};


#endif // GESTUREENUMERATION_HXX_INCLUDED
